
# SEO settings
title: "Mukesh "
title2: "Kharita" # default: ""
# description: "Just another minimalist Jekyll theme for technical writing."
# keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: https://mukeshkharita.github.io/ # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
# disqus_shortname: "hnbloggithub"
twitter_username: "kharita_kumar"
# comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./blog
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Mukesh Kumar Kharita"
  job      : "Software Engineer at Wayfair"
  bio      : "This is my blog."
  thumb    : /images/author.jpg
  email    : mukeshnithcse@gmail.com
  url      : http://mukeshkharita.github.io
  github   : http://github.com/mukeshkharita
  twitter  : http://twitter.com/kharita_kumar
  # facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/kharita

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@kharita_kumar"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
